### ISSUE TITLE
Try Adding a Custom Service

### ISSUE THREAD

**Issue by rocket-turtle** [hundertzehn/mocoapp-browser-extension#10]
Hi,

I tried to build my own chrome extension following this Instructions:
https://github.com/hundertzehn/mocoapp-browser-extension#adding-a-custom-service

When I click on `Erweiterungsoptionen` the Configuration menu to enter the API token does not appear.

When I go back and the Error says:

> Uncaught Error: Bugsnag configuration error "apiKey" is required got null

Am I Doing something wrong?

**Comment by manubo** [comment]
Hi, to solve the issue, please create a `.env` file in the project's root directory with the following content:

`BUGSNAG_API_KEY=invalid`

We will fix this in a following release. Thanks for reporting the issue.

**Comment by rocket-turtle** [comment]
Thank you.

now it is possible to open the `Erweiterungsoptionen` but I get the error `Anmeldung fehlgeschlagen`.

Chrome shows some Warnings an one Error:

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Kontext
background.html
Stacktrace
background.html:0 (Anonyme Funktion)
```

For [bugsnag]:
```
Stacktrace
content.1.1.1.1.js:2061 (startSession)
content.1.1.1.1.js:1455 (startSession)
content.1.1.1.1.js:3358 (_$notifier_2)
content.1.1.1.1.js:40769 (./src/js/utils/notifier.js)
content.1.1.1.1.js:20 (__webpack_require__)
content.1.1.1.1.js:40027 (./src/js/content.js)
content.1.1.1.1.js:20 (__webpack_require__)
content.1.1.1.1.js:84 (Anonyme Funktion)
content.1.1.1.1.js:87 (Anonyme Funktion)
```

Maybe I should wait for the next release.

**Comment by manubo** [comment]
That error usually occurs in Chrome when you upgrade the extension while having opened tabs. The content script in the tabs try to connect to the old background script and fail because it is no longer there. The error should not reoccur after reloading the tabs and  is not the reason you cannot signup on MOCO.

Your error suggests a network error (either missing internet connection or that the server could not be reached). Did you build the the extension with `yarn build:chrome` (the build with `yarn start:chrome` requires a locally running server)? You can also inspect the network request for signup by opening the developer tools in Chrome of the background script:

![inspecting-background-script](https://user-images.githubusercontent.com/871953/55402410-b7742700-5553-11e9-9fc2-bf03c65fd27a.png)

Details of the request would be helpful to find the reason of the failure.

**Comment by rocket-turtle** [comment]
Your right I used `yarn start:chrome` because `yarn build` gives me the error:
```
yarn run v1.15.2
$ yarn build:firefox && yarn zip:firefox && yarn build:chrome && yarn zip:chrome
$ node_modules/.bin/webpack -p --config webpack.firefox.config.js --env.browser firefox --env.NODE_ENV production
clean-webpack-plugin: /Users/user/rails/mocoapp/mocoapp-browser-extension/build/firefox has been removed.
[bugsnag-build-reporter] Invalid payload sent to builds API
[bugsnag-build-reporter]   API key not recognised: invalid
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "moz-extension*://*/background.1.1.1.1.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "moz-extension*://*/content.1.1.1.1.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "moz-extension*://*/options.1.1.1.1.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "moz-extension*://*/popup.1.1.1.1.js"
Error: Unauthorized (401) - invalid apiKey
    at Request.request.post [as _callback] (/Users/user/rails/mocoapp/mocoapp-browser-extension/node_modules/bugsnag-sourcemaps/lib/request.js:23:20)
    at Request.self.callback (/Users/user/rails/mocoapp/mocoapp-browser-extension/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/Users/user/rails/mocoapp/mocoapp-browser-extension/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/Users/user/rails/mocoapp/mocoapp-browser-extension/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1142:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by manubo** [comment]
That error should not occur with `yarn:build`, if you set the `BUGSNAG_API_KEY` as described [earlier here](https://github.com/hundertzehn/mocoapp-browser-extension/issues/10#issuecomment-478875165)

**Comment by rocket-turtle** [comment]
The error only appears if I add the `.env` file like you explained.

If I run the command directly with BUGSNAG_API_KEY set to invalid I get the same error:
`node_modules/.bin/webpack -p --config webpack.chrome.config.js --env.browser chrome --env.NODE_ENV production --env.BUGSNAG_API_KEY invalid`

**Comment by manubo** [comment]
Setting the bugsnag apikey through the `--env` does not work. The api key needs to be defined in the `.env` file. The next version should be out beginnng of next week.
