### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by adrian-goe** [hundertzehn/mocoapp-browser-extension#132]
Hello,
i have written the `remoteServices.js` rules for gitlab and would like to open a PullRequest for it.

Many greetings

**Comment by nethad** [comment]
Hi @adrian-goe 

That sounds great! You should be able to fork this repository and then propose a pull request here. See also: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Let me know if I can help in any way :+1:

**Comment by adrian-goe** [comment]
ah my mistake, i made a pull request

**Comment by nethad** [comment]
Thanks, we'll take a look as soon as possible!

**Comment by nethad** [comment]
PR is merged: https://github.com/hundertzehn/mocoapp-browser-extension/pull/133
