### ISSUE TITLE
Bugsnag tracking

### ISSUE THREAD

**Issue by daugsbi** [hundertzehn/mocoapp-browser-extension#18]
I would like to report that your extension results in additional requests on each page, because of bugsnag.
As a developer I understand the importance of keeping track of potential errors. Although I feel very uncomfortable when an extension sends information even on local developed webapplications without any user interaction. In this case I needed to find out if any of my npm packages implemented bugsnag and finally found your extension responsible for the tracking requests. 

Please limit your use of extension tracking to sites where the extension is needed or when the user interacts with the extension

**Comment by agileapplications** [comment]
We can totally understand your discomfort here and will have a look at this 👍

**Comment by manubo** [comment]
Hi @daugsbi, we decided to remove bugsnag from the extension. Thanks for reporting!

**Comment by manubo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BX: Remove bugsnag](https://trello.com/c/4gC5SKos/4997-bx-remove-bugsnag)

**Comment by manubo** [comment]
https://github.com/hundertzehn/mocoapp-browser-extension/pull/19

**Comment by manubo** [comment]
Hi @daugsbi, we removed bugsnag from the Browser Extension and released version 1.2.2. moments ago: https://github.com/hundertzehn/mocoapp-browser-extension/pull/19

**Comment by daugsbi** [comment]
@manubo thx for the fast fix :+1:
