### ISSUE TITLE
Templating for Rules

### ISSUE THREAD

**Issue by adrian-goe** [hundertzehn/mocoapp-browser-extension#180]
Hello,
we have found that the plugin is practical in many ways. But with some time of use and further development of our internal processes we noticed some limitations.

We thought about solving them in a fork. However, we would like to adjust some things, which makes maintaining the plugin with future updates more difficult.

Therefore we want to present our idea here and talk to you about whether this can be included in the official plugin.

In the code there are the `src/js/remoteServices.js`. Basically this is already a template. But it is not really dynamic and there is no possibility to add your own requirements and tools from outside.
We had thought about changing this so that some functions can be predefined, like parsing a page for a certain attribute.
By using a JSON format each of these options can define how the page is read.
Ideally the rules can be stored on the website and shared for all employees.

Two key features are the extended usability of the plugin for more pages. On the other hand, more details can be captured automatically.

So far this is only an idea. But more can come from a shared idea.

Many greetings

**Comment by nethad** [comment]
Hi Adrian

Sorry for the very late reply. We quickly looked at this and then the follow up with you didn't happen. Right now some of us are on holidays, we'll get back to you soon!

**Comment by manubo** [comment]
Hi Adrian, the idea sound good. `src/js/remoteServices.js` relies on functions to retrieve attributes from a page, and you cannot define functions in JSON. Could you provide an example of a JSON-configuration that would allow to parse a page for a certain attribute, e.g. for the description field of certain service?

**Comment by manubo** [comment]
@adrian-goe If you want to provide an example or more information, we would be glad to further explore and consider this possibility, thanks.

**Comment by adrian-goe** [comment]
Hi, I'm sorry, now I've been on vacation for three weeks. 

A Json could look something like this:
```json
[
  {
    "name": "jira",
    "urlPatterns": [
      "https://:org.atlassian.net/secure/RapidBoard.jspa",
      "https://:org.atlassian.net/browse/:id",
      "https://:org.atlassian.net/jira/software/projects/:projectId/boards/:board",
      "https://:org.atlassian.net/jira/software/projects/:projectId/boards/:board/backlog"
    ],
    "projectId": {
      "type": "URL",
      "selector": "projectId"
    },
    "description": {
      "type": "FIELD",
      "selector": ".ghx-selected .ghx-summary"
    },
    "title": {
      "type": "FIELD",
      "selector": ".ghx-selected .ghx-title"
    },
    "format": ":projectId :title :description"
  },
  {
    "name": "trello",
    "urlPatterns": [
      "https://trello.com/c/:id/:title"
    ],
    "projectId": {
      "type": "URL",
      "selector": "id"
    },
    "title": {
      "type": "FIELD",
      "selector": ".js-title-helper"
    },
    "format": ":projectId :title"
  }
]
```
