### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by quickstar** [hundertzehn/mocoapp-browser-extension#288]
Hi
First of all I like to say thank you for this awesome extension it's a nice timesaver.

According to the blog post [Quick Wins: Zusammenarbeit mit GitLab, Optimierungen an Formularen, Exporten, Erweiterungen der API & Zapier](https://www.mocoapp.com/blog/618-quick-wins-zusammenarbeit-mit-gitlab-optimierungen-an-formularen-exporten-erweiterungen-der-api-zapier) it should be possible to use the browser extension together with Gitlab issues as well. Unfortunately no moco icon appears where I could start log my time. If i use Jira for instance everything works like expected.

Any suggestions?

**Comment by manubo** [comment]
Hi, are you using a self-hosted Gitlab installation? If so, you need to update the URL for the Gitlab-service in the options of the extension.

**Comment by quickstar** [comment]
no we're using the official cloud version https://gitlab.com

**Comment by manubo** [comment]
Please specify the exact problem. I have tested GitLab and it is working as expected. Times can be tracked for issues and merge reuqests. Under which URL do you whish to track time? Have you correctly setup the browser extension in the options?

**Comment by quickstar** [comment]
How is the feature supposed to work? should the experience be similliar to jira/github? If yes, I just don't get the moco "bubble" like I get for example on github as shown in the screenshot:

![image](https://user-images.githubusercontent.com/1195919/106159865-88e22a00-6185-11eb-9c94-74da47db5c65.png)

**Comment by adrian-goe** [comment]
I think there is a problem with gitlab's folder system:
https://gitlab.com/{{organisation/user}}/{{folder}}/{{folder}}/{{project}}/-/{{issues/merge_requests}}/{{issuenumber/MRNumber}}
It is possible to have several subfolders within one organisation. I don't think I had considered that.

**Comment by quickstar** [comment]
> 
> 
> I think there is a problem with gitlab's folder system:
> [https://gitlab.com/{{organisation/user}}/{{folder}}/{{folder}}/{{project}}/-/{{issues/merge_requests}}/{{issuenumber/MRNumber}}](https://gitlab.com/%7B%7Borganisation/user%7D%7D/%7B%7Bfolder%7D%7D/%7B%7Bfolder%7D%7D/%7B%7Bproject%7D%7D/-/%7B%7Bissues/merge_requests%7D%7D/%7B%7Bissuenumber/MRNumber%7D%7D)
> It is possible to have several subfolders within one organisation. I don't think I had considered that.

This is exactly the case in my scenario. My setup looks like this: 
```
- Group
   - Project
      - Repo01
      - Repo02
      - Subproject
         - SubprojectRepo01
         - SubprojectRepo02
      - Repo03
```

**Comment by adrian-goe** [comment]
This MR should solve the problem. I am sorry that I had forgotten about this from the beginning. 🙈

**Comment by adrian-goe** [comment]
@quickstar With the new update, the fix was also published here. I just tested it again with a ticket and merge request.
Thanks @manubo

**Comment by adrian-goe** [comment]
@quickstar I tested your url with the urlMatcher test.
When I replace the `.` in `place.me` it works. I'll see if I can find a solution there.

**Comment by adrian-goe** [comment]
@manubo I think the problem goes a bit, because the UrlMatcher uses the `.` as a delimiter. I don't have any ideas off the top of my head. Do you? 
https://www.npmjs.com/package/url-pattern#named-segments

**Comment by manubo** [comment]
@adrian-goe I will check this week if I can find a quick solution.

**Comment by manubo** [comment]
@adrian-goe @quickstar Please update the project path in Gitlab and, in the project setting, replace the `.` with a `-`, for example. I could not find another solution.
