### ISSUE TITLE
Multiple hosts in settings

### ISSUE THREAD

**Issue by emmue** [hundertzehn/mocoapp-browser-extension#295]
Hello everyone,
are there any plans to allow multiple hosts in the service config? 

We use a self hosted jira in our agency, but also sometimes have to use cloud hosted solutions our clients want to operate themselves in tandem. 

A comma separated list would at least not break too much of the interface for example. 

Hope you have a great day.

**Comment by manubo** [comment]
Hi @emmue, that would be an interesting addition. Do you plan to submit a PR for that?
