### ISSUE TITLE
[BUG] Gitlab issue not recognized, when opening a comment-URL

### ISSUE THREAD

**Issue by infabo** [hundertzehn/mocoapp-browser-extension#468]
When you open a link like https://gitlab.com/sample-group/sample-repo/-/issues/41#note_85970 - the Firefox addon does not recognize it as an Gitlab issue.
When you open https://gitlab.com/sample-group/sample-repo/-/issues/41 instead - the MOCO-icon appears right-bottom corner and the timer is pre-filled with the Gitlab issue #.

**Comment by manubo** [comment]
Hi @infabo Thanks for your report and sorry for the late reply. We will look into this and come back to you.

**Comment by manubo** [comment]
@infabo This is a third-party addition which we do not directly support. You are welcome to submit a PR for this if you like.

**Comment by manubo** [comment]
I think there is a misunderstanding here – looking into it we realised that the Gitlab integration was a contribution from a third party. Here you find all the tools that the Browser-Extension supports:
https://www.mocoapp.com/funktionen/20-connect/inhalt/46-taskmanagement-und-collaboration#380-jira-asana-meistertask-github-clickup-wrike-andere
Community supported tools so far are Gitlab and Monday.com, as mentioned there.

There are hundreds of tools that could be supported by the browser extension. Although we would love to, unfortunately we do not have the resources to support them all. I am sorry that the Gitlab integration is currently not working for you as expected. But being it a community supported integration, we leave it up to interested parties using the Gitlab integration to make sure it works according to their expectations.

**Comment by manubo** [comment]
Hi @adrian-goe, we are receiving reports that the Gitlab integration for the MOCO browser extension is not working as expected. Are you still using it and are you experiencing the same issues like here and here: https://github.com/hundertzehn/mocoapp-browser-extension/issues/484?

**Comment by adrian-goe** [comment]
Hi, currently I don't have a project that uses gitlab issues/MR's for time tracking, so I haven't noticed this before, but was able to reproduce the BUG now.

Turns out, previously gitlab had used an `h2.title` for the title https://github.com/hundertzehn/mocoapp-browser-extension/blob/master/src/js/remoteServices.js#L175
this has changed to `h1.title`. But only for the issues. Fix would be then probably either both as selector to indicate or only `.title`.

I might be able to create an MR by the end of the week. But if you need this faster, feel free to fix this by yourself.

**Comment by infabo** [comment]
Gitlab issue titles are still `h2`.

**Comment by infabo** [comment]
But maybe discuss that over here: #484 484

**Comment by adrian-goe** [comment]
I'm sorry, I have overseen that this are 2 different bugs. so yea https://github.com/hundertzehn/mocoapp-browser-extension/issues/468#issuecomment-1081580428 this is related to the other bug #484

**Comment by adrian-goe** [comment]
Here in the URLs the `#` is missing as a valid path at the end. https://github.com/hundertzehn/mocoapp-browser-extension/blob/master/src/js/remoteServices.js#L169

Probably duplicate each URL and append `#(*)`. But this is just a guess without having tried it directly.

For jira there is something similar https://github.com/hundertzehn/mocoapp-browser-extension/blob/master/src/js/remoteServices.js#L72
