### ISSUE TITLE
GitLab issues no longer tracked with title

### ISSUE THREAD

**Issue by renestalder** [hundertzehn/mocoapp-browser-extension#484]
Somewhen, in the recent updates between now and the past month, the GitLab issue title did no longer appear in the description of the tracked position in Moco.

![Screenshot from 2022-03-28 10-52-26](https://user-images.githubusercontent.com/105358/160362859-2655c133-68aa-4c74-94c3-b37f0783bdbd.png)

_Screenshot of current output in the tracker_

## Expected behaviour

The issue Nr and title to be in the description of the tracked item.

![Screenshot from 2022-03-28 10-56-07](https://user-images.githubusercontent.com/105358/160363049-2a9255d9-2529-49dd-a863-b9c086817c67.png)

_Screenshot of the tracker description back in February_

**Comment by manubo** [comment]
Thanks for your report @renestalder. We will look into this and come back to you.

**Comment by manubo** [comment]
@renestalder This is a third-party addition which we do not directly support. You are welcome to submit a PR for this if you like.

**Comment by infabo** [comment]
@manubo Please stop acting/commenting like a bot. No need to say anything more than "thank you". We all know, that we can submit PRs. So we can report issues. Thanks.
