### ISSUE TITLE
[BUG][FIREFOX] Too long popup URL can't be opened 

### ISSUE THREAD

**Issue by marcopixel** [hundertzehn/mocoapp-browser-extension#570]
We are currently facing an issue where the popup.html can't be opened in Firefox, presumably because of a too long URL passed down (since it does include the projects + last activities as URL encoded JSON). It will simply remove the loading icon and show a white box without contents.

The URL has 1.084.584 characters and will not load inside the iFrame or even when pasted into the address bar, so this seems to be an issue with Firefox not being able to load/open such a long URL. But since this limit might also be on Chrome, it might be in your interest to replace this method of data transmission anyways.

![image](https://user-images.githubusercontent.com/3743025/190379815-48a7ea8b-0032-409b-a541-e27195d3ecc1.png)
![image](https://user-images.githubusercontent.com/3743025/190378142-eef9b0d5-3194-4c18-b8fd-8cad91e76360.png)

I do not know your current status of the migration to v3 (since the latest commit reverted the changes again), but there is an useful library called [`webext-brige`](https://github.com/zikaari/webext-bridge) which allows for much easier messaging inside web extensions. Might be useful if you need to change some stuff for v3 anyways 😉

If you need an working example/repro, feel free to contact me via email on `vockner@futureweb.at` (ENG/DE) 😄

**Comment by agileapplications** [comment]
Hi @marcopixel thank you for the description. We'll look into that. It might take 2 weeks until a fix. Sorry for the inconvenience until then. We'll keep you updated here about the status ☝️

The migration has been reverted due to some issues we discovered afterwards. We'll do another attempt soon. That library might indeed be a great option we'll also verify!

Best Tobias

**Comment by manubo** [comment]
@marcopixel This has been fixed and released with Version 1.9.2. Thanks for reporting!
