### ISSUE TITLE
Overwrite service URLs: Multiple GitLab hosts by regex

### ISSUE THREAD

**Issue by renestalder** [hundertzehn/mocoapp-browser-extension#603]
I'm a bit lost here. Can I actually overwrite the service URLs in the web extension settings (input field) with a regex, so I can match it to multiple random GitLab instances (all having different urls) or is that only possible when I fork the code and change it in the `remoteServices.js`?

Because the description above the input field says, I can use placeholders like `:org`, but also links to the full `remoteServices.js` example that shows regex usage.

**Comment by manubo** [comment]
You can overwrite the service URLs without needing to fork the code and create a custom build. Only one new service URL can be defined per service though, and it depends on the URLs of your GitLab instances whether you can configure the browser extension to work with all of them.

**Comment by renestalder** [comment]
> Only one new service URL can be defined per service though, and it depends on the URLs of your GitLab instances whether you can configure the browser extension to work with all of them.

Yeah, sadly, the part with the one URL is what is the issue. So, that's why I wondered if it takes a regex, something like that:

![Screenshot from 2022-11-08 10-15-57](https://user-images.githubusercontent.com/105358/200524700-02b79048-fe80-4e36-a0ce-be97de78d7c5.png)

That particular example doesn't work because I'm uncertain if it supports regex and, if, which format the field wants.

**Comment by manubo** [comment]
It does not take a regular expression – only possible to add a placeholder, e.g. like `:org`.

**Comment by renestalder** [comment]
Alright, thanks. I will check if I can deliver some kind of pull request for making that UI more dynamic (in case I get the development environment running again locally. Was a bit of a hazzle with getting changes to be applied in Firefox, I guess? Can't remember).

Closing for now.

**Comment by manubo** [comment]
If you submit a PR, we would be happy to consider it. Make sure you read the new requirements for Version 2: https://github.com/hundertzehn/mocoapp-browser-extension#requirements-for-version-2
On Firefox, you need to add the locally build extension as a temporary extension via the URL `about:debugging#/runtime/this-firefox`.
