### ISSUE TITLE
[FEATURE] Remaining budget in hours

### ISSUE THREAD

**Issue by agileapplications** [hundertzehn/mocoapp-browser-extension#607]
- display remaining hours per project/task like in the web view
- only if account activated the feature
- request on change of selected project

![image](https://user-images.githubusercontent.com/235900/201701423-3f0cb505-0c1f-40cb-b2fe-2c00ccb43cb0.png)

**Comment by manubo** [comment]
@DPangerl Es gibt bereits einen API Endpunkt, um die Projektbudgets abzufragen:
`/api/browser_extension/projects/:id/budget`
Weil das eine aufwendige Abfrage ist, sollen die Budgets jeweils nur für das ausgewählte Projekt abgefragt und angezeigt werden. Der Endpunkt liefert auch die Budgets für die Tasks (Leistungen), wenn dort Budgets definiert wurden.
Bei Fragen sag einfach Bescheid.
