### ISSUE TITLE
[FEATURE] MS Planner/Teams integration

### ISSUE THREAD

**Issue by agileapplications** [hundertzehn/mocoapp-browser-extension#608]
Often requested, only possible for the web version, the installable client is out of scope.

**Comment by DPangerl** [comment]
Microsoft planner ([tasks](https://tasks.office.com/)) does not use a dedicated url path for the current task. If you open the details for a task, the url won't update. Though a query parameter `taskId` exists, it is only appended to the url if using a shared link to the specific task. The same goes for the integrated task app within Microsoft Teams. 

This makes it impossible to use the moco extension with the current approach to get information from the url. 
The only view for which we could integrate moco by now is the calendar view within teams. Question is, if this is worth the effort.
