### ISSUE TITLE
The extension no longer works in Firefox

### ISSUE THREAD

**Issue by theofidry** [hundertzehn/mocoapp-browser-extension#613]
I am using Firefox 107.0 (64-bit) on OSX. The extension has been working well for the past year but since two weeks ago it no longer works. I am not sure on how to debug this I do not get any error, but it longer shows the Moco icon on an Asana page.

Is there anyone else experiencing this?

**Comment by manubo** [comment]
Can you please try to deactivate and activate the extension and reload the Asana page. Does it work again if you do that?

**Comment by theofidry** [comment]
I did so and also re-installed it. It worked _for a while_ and then at some point stopped working.

Just now when checking again: clicking on the MOCO extension button _worked_, then checked an Asana page, reloaded it, it stopped working.

Disabling and enabling it back made it work again. Checked the Asana page it worked. Open a fresh new Asana page stopped working†

†: when I say "stop working" I mean that clicking on the MOCO extension in the toolbar does _nothing_ and that checking an Asana page (fresh, reloaded or hard reloaded) does not show the MOCO button that usually shows up.

**Comment by infabo** [comment]
Can confirm issues with recent Firefox versions. The Moco "icon" most of the times do not appear anymore. I could not identify a pattern yet.

**Comment by theofidry** [comment]
It's been a few weeks so an update on my side: despite keeping the extension & Firefox up to date the issue remains. My workaround so far has been to keep a pin tab of the extension, jump there to disable & enable it and then reload whatever page I need Moco on to start the tracking. I need to do that quite often so it's very inconvenient, but at least it kinda works.

**Comment by schnetzi** [comment]
I am having the same problem, but I am using Chrome (Version 108.0.5359.124). The extension keeps stopping working. When disabling and enabling it, it works for one task. After a few minutes it is broken again.

**Comment by manubo** [comment]
Since version 2 we are using Manifest V3 and the webext-bridge package for messaging. We suspect that the extension crashes without being able to recover when the messaging connection is lost, e.g. in a browser upgrade or when the web page of the service updates. We are seeing similar problems here and are still investigating. We hope to fix the issue or to be able to recover properly when an error happens and reconnect the messaging service.

@schnetzi and @theofidry, what service are you using the extension with?

**Comment by theofidry** [comment]
@manubo primarily Asana, but I'm not sure where this is configured as I saw the extension popping up on some non-Asana pages from time to time.

**Comment by lookto** [comment]
Any updates on this? It's not really practical to always have to disable and enable the extension.

Firefox 109.0 (installed via mozillateam/ppa, not snap)
Ubuntu 22.04
Used with Jira

**Comment by manubo** [comment]
We have released Version 2.2.0 of the Browser-Extension with the above mentioned fix. It looks like the Extension runs much more stable now. Feel free to open a new issue should you still have issues in the future.

**Comment by theofidry** [comment]
Will try it out thanks :+1:
