### ISSUE TITLE
Custom Remote Service is no valid Value

### ISSUE THREAD

**Issue by Bernhard-Krop** [hundertzehn/mocoapp-browser-extension#678]
Hello,

I forked this project and added a new custom service for OpenProject. It is working well with one exception: Every time I try to start the clock or add a time, the browser extension gets a 422 reply, telling that the "remote_service" ("openproject") is not a valid value. It seems that your backend is blocking unknown custom services.
How can we add our custom service to our MOCO account, so that the requests get through?

Kind regards,

Bernhard

**Comment by manubo** [comment]
Hi Bernhard, we will add the remote service "openproject". It should be there by tomorrow.

**Comment by Bernhard-Krop** [comment]
Hi Manubo,


sorry for the late response. I was very busy the last few days.

Adding times to MOCO is now working, thanks! I've tested all, again and everything is working fine. Therefor, I've created a [pull request](https://github.com/hundertzehn/mocoapp-browser-extension/pull/680) to make my changes available. Please, review it.


Kind regards,

Bernhard
