### ISSUE TITLE
Option to disable default projects, if no project was detected

### ISSUE THREAD

**Issue by Bernhard-Krop** [hundertzehn/mocoapp-browser-extension#687]
Hi there!

I got a request from a colleague, which I would like to add to this browser extension. Because it is rather specific to my company / that colleague, I would like to discuss this request with you, in what way we could add that request as a feature.

My colleague has the problem, that some tasks are identically labeled across multiple projects. He thinks, that it is easily possible to book time on a task of the wrong project.
For example, there might be a failure regarding the MOCO project ID copying into the label of the remote service's project (e.g. missing the upper case letter or the last digit). In that case, the correct task would not be detected and a default task would be selected; e.g. a task with the same label, but in the wrong project, only because it was the last task he booked time on it.

To prevent this from happening, he wants an empty option in the task selection, which is selected by default, if a task could not be identified without a doubt (by using the MOCO project ID). So he would be able to select the correct task by himself.

I thought about it and my solution would be a checkbox in the extension options, which prevents pre-selection of a task, if it could not be detected by its ID. The default value of this checkbox should be FALSE, meaning no prevention, as it is like today. So nothing would change for people, who are already using the browser extension.

What do you think about it?

Kind regards,

Bernhard

**Comment by manubo** [comment]
As you write, this is a specific problem to your company and colleague and the change would require an additional option. We want to keep the browser extension as simple as possible and each setting option makes the software more complex and with that less maintainable. Sorry for not having a better answer for you.
