### ISSUE TITLE
How to add new Remote Service?

### ISSUE THREAD

**Issue by vdurante** [hundertzehn/mocoapp-browser-extension#719]
I am trying to implement a community service provider for `awork`, but it seems the API calls are not working.

Do you have to enable anything on your backend before I am able to implement on the extension?

Thanks!

**Comment by manubo** [comment]
We will add the remove service `awork` and inform you here when that's done, @vdurante.

**Comment by manubo** [comment]
@vdurante We have merged the PR with the new `awork` remote service. It will be deployed this evening.

**Comment by vdurante** [comment]
Thank you!
