### ISSUE TITLE
Dot in project name

### ISSUE THREAD

**Issue by ArnoEgli** [hundertzehn/mocoapp-browser-extension#737]
The plugin does not recognize the issue url if there is a point in the project. For example https://example.ch/example/example.project/-/issues/2

**Comment by manubo** [comment]
Hi @ArnoEgli, what service are you using? We would need to try to reproduce this, thanks.

**Comment by ArnoEgli** [comment]
Hello @manubo, i'm using Gitlab :)

**Comment by manubo** [comment]
Hi @ArnoEgli, we will add support for a dot in the pathname with the next release.
