### ISSUE TITLE
CSS keyframe animation can potentially change behaviour of websites

### ISSUE THREAD

**Issue by therephil** [hundertzehn/mocoapp-browser-extension#741]
Because the keyframe animate in [_animation.scss](https://github.com/hundertzehn/mocoapp-browser-extension/blob/master/src/css/_animation.scss) is not namespaced or otherwise scoped it pollutes and potentially overwrites other keyframe animations with the same name on a random website. `fadeIn` is a name other people could use as well.

see for example here:
https://www.hibike.de/fahrradteile-n52f1161237298

where the sidebar with all the filters is hidden after a short flash because they use the same animaten name just animate a different property.

**Comment by manubo** [comment]
Thanks @therephil, this will be fixed with the next release.
