### ISSUE TITLE
Memorize selected Project

### ISSUE THREAD

**Issue by EdwardBock** [hundertzehn/mocoapp-browser-extension#893]
Hi there,

first of all thanks for this great extension. Works fine, but it would be great if you could save the selected project on a project level.

Example:

1. Start tracking to gitlab.com/group/project-1/-/issues/1 on Moco Project 1 
2. I switch to gitlab.com/group/project-2/-/issues/1 and start tracking on Project 2
3. Now I switch back to  gitlab.com/group/project-1/-/issues/1 and I really would like to have Project 1 preselected

This would prevent me to track on the wrong project.

Thanks!

**Comment by manubo** [comment]
Hi @EdwardBock 

The Gitlab service is a community supported service in the MOCO Browser Extension (it is registered in the file named `remoteServicesCommunity.js`).

The pre-selected project and be configured for the service via `projectId` and `projectLabel` in the service-definition, as described in the [docs](https://github.com/hundertzehn/mocoapp-browser-extension?tab=readme-ov-file#remote-service-configuration). There are other services using this approach, e.g. `awork`, `basecamp3`, `openproject` and `superchat`.

We would welcome a PR for the Gitlab-service, thanks!
