### ISSUE TITLE
Default description

### ISSUE THREAD

**Issue by EdwardBock** [hundertzehn/mocoapp-browser-extension#894]
The current default description is:

```
#{issue_number} {issue_title}
```

First the `#{number}` syntax seems to be a special token in the moco ui which is misleading.

Second it would be great to have the url to the ticket in the description like:

```
Issue {issue_number} ${issue_title}

{https://gitlab.com/group/project/-/issues/{issue_number}
```

Thanks!

**Comment by manubo** [comment]
Hi @EdwardBock 

The Gitlab service is a community supported service in the MOCO Browser Extension (it is registered in the file named `remoteServicesCommunity.js`).

We would welcome and consider any addition you have for the Gitlab-service as a PR, thanks!
